on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        dotnet-version: ["5.0.x"]
    defaults:
      run:
        working-directory: ./src
    timeout-minutes: 15
    steps:
      - name: Check nuget access key
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}
        run: echo auth | echo ${NUGET_AUTH_TOKEN}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release --no-build
