on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        dotnet-version: ["5.0.x"]
    defaults:
      run:
        working-directory: ./src
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo git ref
        run: echo $env:GITHUB_REF
      - name: Echo git tags 2
        run: echo $env:GITHUB_REF -replace 'refs\/tags\/'
      - name: Echo git tags
        run: echo $(git describe --tags --abbrev=0)
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release --no-build
