on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        dotnet-version: ["5.0.x"]
    defaults:
      run:
        working-directory: ./src
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo git ref
        run: echo $GITHUB_REF
      - name: Echo git ref 2
        env:
          REF: ${{ github.ref }}
        run: echo $env:REF
      - name: Echo git tags
        run: echo ${GITHUB_REF/refs\/tags\//}
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release --no-build
