name: dotnet package
on: [push]
jobs:
  publish:
    runs-on: self-hosted
    strategy:
      matrix:
        dotnet-version: ["5.0.x"]

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}
      - name: Open src dir
        run: cd src
      - name: list
        run: ls
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --verbosity normal --no-build
      - name: Create the package
        run: dotnet pack --configuration Release src/TextDetection.csproj
      - name: Publish the package to GPR
        run: dotnet nuget push TextDetection/bin/Release/*.nupkg
