name: dotnet package
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  publish:
    runs-on: self-hosted
    strategy:
      matrix:
        dotnet-version: ["5.0.x"]
    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Verify commit exists in origin/master
        run: git branch --remote --contains | Select-String 'origin/master'
      - name: get git tag
        uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "(.*)" # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --verbosity normal
      - name: Create detection package
        run: dotnet pack --configuration Release Ok.TextRecognition.Detection/Ok.TextRecognition.Detection.csproj
      - name: Publish detection package
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}
        run: dotnet nuget push Ok.TextRecognition.Detection/bin/Release/Ok.TextRecognition.Detection.$env:GIT_TAG_NAME.nupkg --source https://api.nuget.org/v3/index.json --api-key $env:NUGET_AUTH_TOKEN
      - name: Create recognition package
        run: dotnet pack --configuration Release Ok.TextRecognition.Recognition/Ok.TextRecognition.Recognition.csproj
      - name: Publish recognition package
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}
        run: dotnet nuget push Ok.TextRecognition.Recognition/bin/Release/Ok.TextRecognition.Recognition.$env:GIT_TAG_NAME.nupkg --source https://api.nuget.org/v3/index.json --api-key $env:NUGET_AUTH_TOKEN
